apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: concourse-web
  namespace: concourse
  labels:
    app: web
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
