concourse:
  web:
    enabled: true
    externalUrl: "unjinxed.dev:8081"
  worker:
    enabled: true
  service:
    web:
      type: NodePort
      ports:
        http: 8080
  postgresql:
    auth:
      password: <+serviceVariables.postgresqlPassword>
  secrets:
    localUsers: <+serviceVariables.concourseUsername>:<+serviceVariables.concoursePassword>

  ingress:
    enabled: true
    hostname: unjinxed.dev
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        kubernetes.io/ingress.class: "nginx" 
