concourse:
  web:
    enabled: true
    externalUrl: "unjinxed.dev:8080"
    # baseUrl: "/ci"
    containerPorts:
      http: 8081
  worker:
    enabled: true
  service:
    web:
      type: NodePort
      ports:
        http: 8080
  postgresql:
    auth:
      password: <+serviceVariables.postgresqlPassword>
  secrets:
    localUsers: <+serviceVariables.concourseUsername>:<+serviceVariables.concoursePassword>

  ingress:
    enabled: true
    hostname: concourse.dev
    annotations:
        kubernetes.io/ingress.class: "nginx"
