concourse:
  web:
    enabled: true
    # externalUrl: "192.168.1.101:8080"
  worker:
    enabled: true
    # containerPorts:
    #   http: 8081
  service:
    web:
      type: NodePort
      ports:
        http: 8081
  postgresql:
    auth:
      password: <+serviceVariables.postgresqlPassword>
  secrets:
    localUsers: <+serviceVariables.concourseUsername>:<+serviceVariables.concoursePassword>

  ingress:
    enabled: true
    # hostname: unjinxed.dev
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        kubernetes.io/ingress.class: "nginx"
    extraRules:
    - host: 192.168.1.101
      http:
        path: /
        backend:
          service:
            name: concourse-svc
