concourse:
  web:
    enabled: true
    externalUrl: "192.168.1.101"
  worker:
    enabled: true
  service:
    web:
      type: NodePort
  postgresql:
    auth:
      password: <+serviceVariables.postgresqlPassword>
  secrets:
    localUsers: <+serviceVariables.concourseUsername>:<+serviceVariables.concoursePassword>

  ingress:
    enabled: true
    # hostname: unjinxed.dev
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        kubernetes.io/ingress.class: "nginx"
    extraRules:
    - host: 192.168.1.101
      http:
        path: /
        backend:
          service:
            name: concourse-svc
            port:
              name: 8080
